export class Stats {
    bonusReceptionsTightEnd: number;
    receptionsDropped: number;
    bonusReceivingYards100: number;
    positionRankStandard: number;
    gamesPlayed: number;
    rankHalfPPR: number;
    receptions0To4Yards: number;
    teamDefensiveSnaps: number;
    firstTouchdowns: number;
    gamesActive: number;
    penalties: number;
    receivingTouchdowns: number;
    receivingYardsPerTarget: number;
    receptions20To29Yards: number;
    rankStandard: number;
    positionRankHalfPPR: number;
    specialTeamsSnaps: number;
    pointsStandard: number;
    longestReception: number;
    teamSpecialTeamsSnaps: number;
    bonusRushingReceivingYards100: number;
    receptions: number;
    receivingYards: number;
    receptionsFirstDown: number;
    receptions5To9Yards: number;
    gamesStarted: number;
    teamOffensiveSnaps: number;
    positionRankPPR: number;
    rankPPR: number;
    receptionsRedZoneTargets: number;
    penaltyYards: number;
    receptions40PlusYards: number;
    offensiveSnaps: number;
    pointsHalfPPR: number;
    receptionsAirYards: number;
    receivingYardsPerReception: number;
    receptions10To19Yards: number;
    longestReceivingTouchdown: number;
    rushingReceivingYards: number;
    anytimeTouchdowns: number;
    receptionsTargets: number;
    fumbles: number;
    pointsPPR: number;
    bonusFirstDownTightEnd: number;

    constructor(data: any) {
        this.bonusReceptionsTightEnd = data.bonus_rec_te;
        this.receptionsDropped = data.rec_drop;
        this.bonusReceivingYards100 = data.bonus_rec_yd_100;
        this.positionRankStandard = data.pos_rank_std;
        this.gamesPlayed = data.gp;
        this.rankHalfPPR = data.rank_half_ppr;
        this.receptions0To4Yards = data.rec_0_4;
        this.teamDefensiveSnaps = data.tm_def_snp;
        this.firstTouchdowns = data.first_td;
        this.gamesActive = data.gms_active;
        this.penalties = data.penalty;
        this.receivingTouchdowns = data.rec_td;
        this.receivingYardsPerTarget = data.rec_ypt;
        this.receptions20To29Yards = data.rec_20_29;
        this.rankStandard = data.rank_std;
        this.positionRankHalfPPR = data.pos_rank_half_ppr;
        this.specialTeamsSnaps = data.st_snp;
        this.pointsStandard = data.pts_std;
        this.longestReception = data.rec_lng;
        this.teamSpecialTeamsSnaps = data.tm_st_snp;
        this.bonusRushingReceivingYards100 = data.bonus_rush_rec_yd_100;
        this.receptions = data.rec;
        this.receivingYards = data.rec_yar;
        this.receptionsFirstDown = data.rec_fd;
        this.receptions5To9Yards = data.rec_5_9;
        this.gamesStarted = data.gs;
        this.teamOffensiveSnaps = data.tm_off_snp;
        this.positionRankPPR = data.pos_rank_ppr;
        this.rankPPR = data.rank_ppr;
        this.receptionsRedZoneTargets = data.rec_rz_tgt;
        this.penaltyYards = data.penalty_yd;
        this.receptions40PlusYards = data.rec_40p;
        this.offensiveSnaps = data.off_snp;
        this.pointsHalfPPR = data.pts_half_ppr;
        this.receptionsAirYards = data.rec_air_yd;
        this.receivingYardsPerReception = data.rec_ypr;
        this.receptions10To19Yards = data.rec_10_19;
        this.longestReceivingTouchdown = data.rec_td_lng;
        this.rushingReceivingYards = data.rush_rec_yd;
        this.anytimeTouchdowns = data.anytime_tds;
        this.receptionsTargets = data.rec_tgt;
        this.fumbles = data.fum;
        this.pointsPPR = data.pts_ppr;
        this.bonusFirstDownTightEnd = data.bonus_fd_te;
    }
}